name: Build LaTeX document
on:
  push:	
    branches:	
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: ms_thesis.tex
          working_directory: stthesis_latex/
      - name: upload compiled pdf
        uses: actions/upload-artifact@v1
        with:
          name: ms_thesis.pdf
          path: ./stthesis_latex/ms_thesis.pdf
